### PR TITLE
Corrected percent difference calculations in compare scenarios Rmd template

### PR DESCRIPTION
**Pull request by landisrm**
This resolves issue [#93](https://github.com/tlumip/tlumip/issues/93).

### CODE REVIEW

**Comment by bstabler** [comment]
I'm not sure if we want to restore the ability to get zones if using a database that doesn't have them added?  @bettinardi - what do you think?  Moving forward, do we want to assume the zones will be in the databases?

**Comment by bettinardi** [comment]
It will be tricky to work this in.  My thoughts on preferred options:
1. The code checks for zones, gets them if they are there and comes up with a different solution if it's an old data base where they don't exist
2.  (my vote if possible) - the old swimr still works with our existing runs.  Issue - https://github.com/tlumip/tlumip/issues/95 works swimr into the SWIM run flow.  My favorite idea is that all of these updates are kept in development until swimr is released in the SWIM run flow.  That way it can help ensure that all of the required pre-reqs for swimr have been created.

The third cheapest option, is to carefully navigate what version of swimr is used with what version of the SWIM database - my least favorite option.

**Comment by bstabler** [comment]
I just talked with @bettinardi and we're going to do the following:
  - the swimr package needs to be backwards compatible - it needs to support the old and new zone polygon setup
  - @landisrm please update the package so the user can configure which option to use.  Maybe something like this?
    - zonesInDatabase = true
    - zonesInDatabase = false (and so use the zones25 files)
  - Delete all the zones26 files since they are not needed 

Once this is complete, @bettinardi can install the package and start using it with old and new swim runs.  We're going to hold off on starting tlumip issue [#95](https://github.com/tlumip/tlumip/issues/95)

**Comment by bstabler** [comment]
this is done

**Pull request merged**
